// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import StoreProvider from "@/store/StoreProvider";
// import IntlProviderWrapper from "@/components/IntlProviderWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>
//         <StoreProvider>
//           <IntlProviderWrapper>{children}</IntlProviderWrapper>
//         </StoreProvider>
//       </body>
//     </html>
//   );
// }
// src/app/layout.tsx
import type { Metadata } from 'next'
import StoreProvider from '@/store/StoreProvider'
import IntlProviderWrapper from '@/components/IntlProviderWrapper'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'
import '@/index.scss'

export const metadata: Metadata = {
  title: {
    default: 'Animoxkart | Pet Store',
    template: '%s | Animoxkart',
  },
  description:
    'Discover a world of comfort and style for your loveable pets at Animoxkart. Explore our exclusive collection of dog products.',
  keywords: ['pet store', 'dog accessories', 'dog harness', 'dog leash', 'dog collar'],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" id="color" href="/assets/css/color1.css" />
      </head>
      <body>
        <StoreProvider>
          <IntlProviderWrapper>
            {children}
          </IntlProviderWrapper>
        </StoreProvider>
      </body>
    </html>
  )
}